// Generated by CoffeeScript 1.7.1
var ServerProcessManager, path, spawn, util;

spawn = require('child_process').spawn;

path = require('path');

util = require('util');

ServerProcessManager = (function() {

  /*
  Manages cordjs development web-server process starting/stopping/restarting
   */
  ServerProcessManager.prototype._process = null;

  ServerProcessManager.prototype._errorCounter = 0;

  ServerProcessManager.prototype._resetErrorCounterTimeout = null;

  function ServerProcessManager(params) {
    this.params = params;
  }

  ServerProcessManager.prototype.start = function() {
    if (!this._process) {
      this._process = spawn('node', [path.join(this.params.targetDir, 'server.js'), path.join(this.params.targetDir, 'public'), this.params.config, this.params.port], {
        cwd: this.params.targetDir
      });
      this._process.stdout.on('data', util.print);
      this._process.stderr.on('data', util.print);
      this._process.on('exit', (function(_this) {
        return function(code) {
          if (_this._errorCounter > 1) {
            return util.log("Too many restart errors. Stopping to try. Error code '" + code + "'");
          } else {
            _this._errorCounter++;
            return _this.restart();
          }
        };
      })(this));
      if (this._resetErrorCounterTimeout != null) {
        clearTimeout(this._resetErrorCounterTimeout);
      }
      return this._resetErrorCounterTimeout = setTimeout((function(_this) {
        return function() {
          return _this._errorCounter = 0;
        };
      })(this), 1000);
    } else {
      return console.warn("Server process is already started!");
    }
  };

  ServerProcessManager.prototype.stop = function() {
    if (this._process) {
      this._process.removeAllListeners('exit');
      this._process.kill();
      return this._process = null;
    }
  };

  ServerProcessManager.prototype.restart = function() {
    this.stop();
    return this.start();
  };

  return ServerProcessManager;

})();

module.exports = ServerProcessManager;
