// Generated by CoffeeScript 1.7.1
var HeuristicGroupDetector, sha1, _;

_ = require('underscore');

sha1 = require('../utils/sha1');

HeuristicGroupDetector = (function() {
  HeuristicGroupDetector.prototype._countMap = null;

  HeuristicGroupDetector.prototype._curStat = null;

  HeuristicGroupDetector.prototype._maxGroupScore = 0;

  HeuristicGroupDetector.prototype._thresholdTime = 0;

  function HeuristicGroupDetector(groupRepo) {
    this.groupRepo = groupRepo;
  }

  HeuristicGroupDetector.prototype.process = function(stat) {
    var group, lengthBefore, module, moduleList, moduleMap, modules, optimizedStat, page, pages, remaining, resultGroups, _i, _j, _len, _len1, _ref, _ref1;
    this._countMap = {};
    _ref = this._mapStat(stat);
    for (module in _ref) {
      pages = _ref[module];
      this._countMap[module] = pages.length;
    }
    this._curStat = {};
    for (page in stat) {
      moduleList = stat[page];
      this._curStat[page] = {};
      for (_i = 0, _len = moduleList.length; _i < _len; _i++) {
        module = moduleList[_i];
        this._curStat[page][module] = true;
      }
    }
    remaining = Object.keys(this._countMap);
    remaining = _.sortBy(remaining, (function(_this) {
      return function(m) {
        return _this._countMap[m];
      };
    })(this)).reverse();
    resultGroups = [];
    while (true) {
      group = this._findBestGroup(remaining);
      if (group !== false) {
        remaining = _.difference(remaining, group.getItems());
        remaining = (_.sortBy(remaining, (function(_this) {
          return function(m) {
            return _this._countMap[m];
          };
        })(this))).reverse();
        resultGroups.push(group);
        _ref1 = this._curStat;
        for (page in _ref1) {
          moduleMap = _ref1[page];
          this._curStat[page] = _.omit(moduleMap, group.getItems());
          if (Object.keys(this._curStat[page]).length === 0) {
            delete this._curStat[page];
          }
        }
      } else {
        break;
      }
    }
    optimizedStat = {};
    for (page in stat) {
      moduleList = stat[page];
      modules = _.clone(moduleList);
      for (_j = 0, _len1 = resultGroups.length; _j < _len1; _j++) {
        group = resultGroups[_j];
        lengthBefore = modules.length;
        modules = _.difference(modules, group.getItems());
        if (lengthBefore > modules.length) {
          modules.push(group.id);
        }
      }
      optimizedStat[page] = modules;
    }
    return optimizedStat;
  };

  HeuristicGroupDetector.prototype._findBestGroup = function(moduleList) {
    var duration, groups, i, item, _i, _len;
    groups = [];
    this._maxGroupScore = 0;
    this._thresholdTime = (new Date).getTime() + 120000;
    for (i = _i = 0, _len = moduleList.length; _i < _len; i = ++_i) {
      item = moduleList[i];
      groups = groups.concat(this._collectGroups([], moduleList, i, Object.keys(this._curStat), 0));
      if ((new Date).getTime() >= this._thresholdTime) {
        console.warn("Optimizer: interrupting calculation due to threshold time achieving!");
        break;
      }
    }
    duration = ((new Date).getTime() - (this._thresholdTime - 120000)) / 1000;
    if (duration > 5) {
      console.log("Found best group in", duration, "seconds");
    }
    if (groups.length > 0) {
      _.sortBy(groups, function(item) {
        return item[1];
      }).reverse();
      return this.groupRepo.createGroup(this._generateGroupId(groups[0][2]), groups[0][2]);
    } else {
      return false;
    }
  };

  HeuristicGroupDetector.prototype._collectGroups = function(prevGroup, list, startIndex, checkPages, level) {

    /*
    Recursive module group collector
    @param Array[String] prevGroup  accumulated on previous level existing group
    @param Array[String] list       source list of modules to process
    @param Int           startIndex which item of the list to start from (every recursive call must increase it)
    @param Array[String] checkPages short-list of pages to be used to check group existence (shortened by previous level)
    @param Int           level      nesting level for debugging
    @return Array[Array[(Int, Int, Array[String])]]
     */
    var avg, cnt, group, i, index, matchPages, result, score, scoreArr, summ, _i, _ref, _ref1;
    result = [];
    if ((new Date).getTime() < this._thresholdTime) {
      for (i = _i = startIndex, _ref = list.length; startIndex <= _ref ? _i <= _ref : _i >= _ref; i = startIndex <= _ref ? ++_i : --_i) {
        _ref1 = this._groupExists(list[i], checkPages), cnt = _ref1[0], matchPages = _ref1[1];
        if (cnt > 0) {
          group = prevGroup.concat([list[i]]);
          scoreArr = _.map(group, (function(_this) {
            return function(m) {
              return [m, _this._countMap[m]];
            };
          })(this));
          summ = _.reduce(scoreArr, (function(res, item) {
            return res + item[1];
          }), 0);
          avg = summ / group.length;
          index = _.reduce(scoreArr, function(res, item) {
            var deviation;
            deviation = Math.abs(item[1] - avg);
            if (deviation < res[0]) {
              return [deviation, item[1]];
            } else {
              return res;
            }
          }, [2000000000, 0]);
          scoreArr = _.filter(scoreArr, function(item) {
            return Math.abs(item[1] - index[1]) <= 1;
          });
          score = cnt * scoreArr.length;
          if (score > this._maxGroupScore && group.length > 1) {
            result.push([cnt, score, group]);
            this._maxGroupScore = score;
            if ((new Date).getTime() > this._thresholdTime - 30000) {
              console.log("Optimizer: increasing threshold time...");
              this._thresholdTime += 30000;
            }
          }
          result = result.concat(this._collectGroups(group, list, i + 1, matchPages, level + 1));
        }
      }
    }
    return result;
  };

  HeuristicGroupDetector.prototype._groupExists = function(checkModule, checkPages) {

    /*
    Returns count of pages in which the given module is used.
    @param String checkModule module to check
    @param Array[String] checkPages list of pages to check
    @return Int
     */
    var count, matchPages, page, _i, _len;
    count = 0;
    matchPages = [];
    for (_i = 0, _len = checkPages.length; _i < _len; _i++) {
      page = checkPages[_i];
      if (this._curStat[page][checkModule]) {
        count++;
        matchPages.push(page);
      }
    }
    return [count, matchPages];
  };

  HeuristicGroupDetector.prototype._mapStat = function(stat) {
    var module, moduleList, page, result, _i, _len;
    result = {};
    for (page in stat) {
      moduleList = stat[page];
      for (_i = 0, _len = moduleList.length; _i < _len; _i++) {
        module = moduleList[_i];
        if (module.indexOf('/bundles/cord/core/init/browser-init.js') === -1) {
          if (result[module] == null) {
            result[module] = [];
          }
          result[module].push(page);
        }
      }
    }
    return result;
  };

  HeuristicGroupDetector.prototype._generateGroupId = function(items) {
    var itemsStr;
    itemsStr = items.sort().join();
    return 'group-heuristic-' + sha1(itemsStr) + '-' + items.length + '-' + itemsStr.substr(-12);
  };

  return HeuristicGroupDetector;

})();

module.exports = HeuristicGroupDetector;
