// Generated by CoffeeScript 1.9.1
var CssOptimizer, Future, JsOptimizer, Optimizer, _, browserInitGenerator, fs, mkdirp, rmrf, sha1;

fs = require('fs');

_ = require('underscore');

mkdirp = require('mkdirp');

Future = require('../utils/Future');

rmrf = require('../utils/rmrf');

sha1 = require('../utils/sha1');

browserInitGenerator = require('./browserInitGenerator');

CssOptimizer = require('./CssOptimizer');

JsOptimizer = require('./JsOptimizer');

Optimizer = (function() {

  /*
  Build optimizer.
  * grouping modules into single files
  * minifying, gzipping
  * and so on
   */
  Optimizer.prototype._zDir = null;

  Optimizer.prototype._requireConfig = null;

  Optimizer.prototype._cleanFuture = null;

  function Optimizer(params) {
    this.params = params;
    this._zDir = this.params.targetDir + "/public/assets/z";
  }

  Optimizer.prototype.run = function() {
    var cssOptimizerPromise, jsOptimizerPromise, start, zDirFuture;
    start = process.hrtime();
    zDirFuture = (this.params.clean ? rmrf(this._zDir) : Future.resolved()).then((function(_this) {
      return function() {
        return Future.call(mkdirp, _this._zDir);
      };
    })(this));
    cssOptimizerPromise = this.params.css ? (new CssOptimizer(this.params, zDirFuture)).run() : Future.call(fs.unlink, this.params.targetDir + "/conf/css-to-group-generated.js").then(function() {
      return {};
    })["catch"](function() {
      return {};
    });
    jsOptimizerPromise = this.params.js ? (new JsOptimizer(this.params, zDirFuture)).run() : Future.resolved({});
    return Future.all([jsOptimizerPromise, cssOptimizerPromise]).spread((function(_this) {
      return function(jsGroupMap, cssGroupMap) {
        var browserInitPromise;
        console.log("Generating browser-init script...");
        browserInitPromise = browserInitGenerator.generate(_this.params, jsGroupMap, cssGroupMap).then(function(browserInitScriptString) {
          var fileName;
          fileName = sha1(browserInitScriptString);
          return Future.all([Future.call(fs.writeFile, _this._zDir + "/" + fileName + ".js", browserInitScriptString), Future.call(fs.writeFile, _this._zDir + "/browser-init.id", fileName)]);
        });
        return Future.all([browserInitPromise, _this._saveGroupMapCacheFile(jsGroupMap, cssGroupMap)]);
      };
    })(this)).then(function() {
      var diff;
      diff = process.hrtime(start);
      return console.log("Optimization complete in " + ((diff[0] * 1e9 + diff[1]) / 1e6) + " ms");
    }).failAloud('Optimizer::run');
  };

  Optimizer.prototype._saveGroupMapCacheFile = function(jsGroupMap, cssGroupMap) {

    /*
    Saves optimizer's computed groups mapping into the cache file for later use by `purgeOptimizedSources` command.
    @param {Object} jsGroupMap
    @param {Object} cssGroupMap
    @return {Future<undefined>}
     */
    var css, cssToGroup, file, fileName, groupId, i, j, jsToGroup, len, len1, mergedMap, urls;
    jsToGroup = {};
    for (groupId in jsGroupMap) {
      urls = jsGroupMap[groupId];
      for (i = 0, len = urls.length; i < len; i++) {
        file = urls[i];
        jsToGroup[file] = groupId;
      }
    }
    cssToGroup = {};
    for (groupId in cssGroupMap) {
      urls = cssGroupMap[groupId];
      for (j = 0, len1 = urls.length; j < len1; j++) {
        css = urls[j];
        cssToGroup[css] = groupId;
      }
    }
    mergedMap = {
      js: jsToGroup,
      css: cssToGroup
    };
    fileName = this.params.targetDir + "/conf/optimizer-group-cache-generated.js";
    return Future.call(fs.writeFile, fileName, "module.exports = " + (JSON.stringify(mergedMap, null, 2)) + ";");
  };

  return Optimizer;

})();

module.exports = Optimizer;
