// Generated by CoffeeScript 1.9.1
var Future, _, appConfig, path, pathConfigFile, requirejs, savedConfigFuture;

path = require('path');

_ = require('lodash');

requirejs = require(process.cwd() + '/node_modules/requirejs');

Future = require('../utils/Future');

appConfig = require('../appConfig');

pathConfigFile = 'public/bundles/cord/core/requirejs/pathConfig';

savedConfigFuture = null;

exports.collect = function(targetDir) {

  /*
  Collects and merges requirejs configuration into single config object from the different sources:
  * cordjs path-config
  * enabled bundles configs
  @param String targetDir directory with compiled cordjs project
  @return Future[Object]
   */
  var pathConfig, resultConfig;
  if (savedConfigFuture) {
    return savedConfigFuture;
  } else {
    pathConfig = require("" + (path.join(targetDir, pathConfigFile)));
    resultConfig = {
      baseUrl: '/',
      urlArgs: 'release=' + Math.random(),
      paths: pathConfig
    };
    requirejs.config({
      baseUrl: path.join(targetDir, 'public'),
      paths: pathConfig
    });
    return savedConfigFuture = appConfig.getBundles(targetDir).then(function(bundles) {
      var bundle, configs;
      configs = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = bundles.length; i < len; i++) {
          bundle = bundles[i];
          results.push("cord!/" + bundle + "/config");
        }
        return results;
      })();
      return Future.require(configs);
    }).then(function(configs) {
      var config, i, len;
      for (i = 0, len = configs.length; i < len; i++) {
        config = configs[i];
        if (config.requirejs) {
          _.merge(resultConfig, config.requirejs);
        }
      }
      return resultConfig;
    });
  }
};
