// Generated by CoffeeScript 1.3.3
var Generator, bundleGenerator, createDir, exec, fs, path, projectGenerator, sendCommand, spawn, sys, util, utils, _ref,
  __slice = [].slice;

fs = require('fs');

util = require('util');

path = require('path');

sys = require('sys');

_ref = require('child_process'), spawn = _ref.spawn, exec = _ref.exec;

exports.VERSION = '0.0.4';

Generator = {
  collection: {},
  addGenerator: function(name, callback) {
    return this.collection[name] = callback;
  },
  exists: function(name) {
    return !!this.collection[name];
  },
  "do": function() {
    var args, name, _ref1;
    name = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return (_ref1 = this.collection)[name].apply(_ref1, args);
  },
  list: function() {
    return Object.keys(this.collection).join(', ');
  },
  init: function() {
    this.addGenerator('project', projectGenerator);
    return this.addGenerator('bundle', bundleGenerator);
  }
};

projectGenerator = function(command, args) {
  switch (command) {
    case "create":
      utils.timeLog('Cloning based project layout...');
      return sendCommand("git clone https://github.com/cordjs/cordjs.git .", function() {
        createDir('public/bundles/cord');
        createDir('public/bundles/cord/core');
        console.log('Cloning core...');
        return sendCommand("git clone https://github.com/cordjs/core.git public/bundles/cord/core");
      });
    case "update":
      return sendCommand("git pull");
  }
};

bundleGenerator = function(command, args) {
  var bundleName;
  switch (command) {
    case "create":
      bundleName = args.shift();
      if (!bundleName) {
        console.log('Error: Empty bandle name');
        process.exit();
      }
      createDir(path.join("public/bundles", bundleName));
      return console.log("Bundle " + bundleName + " create!");
  }
};

Generator.init();

exports.Generator = Generator;

createDir = function(dir) {
  var pathDir, root;
  root = process.cwd();
  pathDir = path.join(root, dir);
  if (!fs.existsSync(pathDir)) {
    return fs.mkdirSync(path.join(root, dir), '0755');
  }
};

sendCommand = function(command, callback) {
  return exec(command, function(error, stdout, stderr) {
    if (error) {
      console.log("" + error);
    } else {
      if (stdout) {
        console.log(stdout);
      }
    }
    return typeof callback === "function" ? callback.apply(null, arguments) : void 0;
  });
};

utils = {
  timeLog: function(message) {
    return console.log("" + ((new Date).toLocaleTimeString()) + " - " + message);
  },
  timeLogError: function(message) {
    return console.log("");
  }
};

exports.utils = utils;
