// Generated by CoffeeScript 1.9.1
(function() {
  var Future, appConfFile, path, requirejs, savedBundlesFuture;

  path = require('path');

  requirejs = require(process.cwd() + '/node_modules/requirejs');

  Future = require('./utils/Future');

  appConfFile = 'app/application';

  savedBundlesFuture = null;

  exports.getBundles = function(targetDir) {

    /*
    Loads application config and returns list of bundles of the application including core bundle.
    @param String targetDir directory with compiled cordjs project
    @return Future[Array[String]]
     */
    if (savedBundlesFuture) {
      return savedBundlesFuture;
    } else {
      requirejs.config({
        baseUrl: path.join(targetDir, 'public')
      });
      savedBundlesFuture = Future.require(appConfFile).then(function(bundles) {
        return [['cord/core'].concat(bundles)];
      });
      return savedBundlesFuture;
    }
  };

}).call(this);
