// Generated by CoffeeScript 1.6.3
var Optimizer, ProjectBuilder, ServerProcessManager, cliParser, normalizeBuildOptions, normalizeServerOptions, rmrf, _;

_ = require('underscore');

rmrf = require('./utils/rmrf');

cliParser = require('./cli-parser');

Optimizer = require('./optimizer/Optimizer');

ProjectBuilder = require('./build/ProjectBuilder');

ServerProcessManager = require('./server/ServerProcessManager');

exports.main = function() {
  /*
  Main cordjs CLI tool entry point.
  */

  return cliParser.run({
    build: function(options) {
      /*
      Builds whole project.
      */

      var builder;
      console.log("Building project with options", options);
      builder = new ProjectBuilder(normalizeBuildOptions(options));
      return builder.build();
    },
    run: function(options) {
      /*
      Builds project and starts cordjs server
      */

      var buildOptions, builder, serverOptions, serverProcessManager;
      buildOptions = normalizeBuildOptions(options);
      builder = new ProjectBuilder(buildOptions);
      builder.build();
      serverOptions = normalizeServerOptions(options);
      serverProcessManager = new ServerProcessManager(_.extend(buildOptions, serverOptions));
      return builder.on('complete', function() {
        console.log("build complete. restarting...");
        return serverProcessManager.restart();
      });
    },
    optimize: function(options) {
      var optimizer;
      optimizer = new Optimizer;
      return optimizer.run();
    },
    clean: function(options) {
      console.log("Cleaning project...");
      return rmrf(normalizeBuildOptions(options).targetDir);
    }
  });
};

normalizeBuildOptions = function(options) {
  var curDir;
  if (options.parent.chdir) {
    process.chdir(options.parent.chdir);
  }
  curDir = process.cwd();
  return {
    baseDir: curDir,
    targetDir: "" + curDir + "/" + options.out,
    watch: !!options.watch,
    debug: !!options.debug
  };
};

normalizeServerOptions = function(options) {
  return {
    config: options.config,
    port: parseInt(options.port)
  };
};
