// Generated by CoffeeScript 1.9.1
var path, normalizePathSeparator;

path = require('path');

normalizePathSeparator = function(filePath) {
  return filePath.split(path.sep).join('/');
};

module.exports = normalizePathSeparator;
