// Generated by CoffeeScript 1.6.3
var defineFuture,
  __slice = [].slice;

defineFuture = function(_) {
  var Future, throwExceptionCallback;
  throwExceptionCallback = function(err) {
    throw err;
  };
  return Future = (function() {
    /*
    Simple aggregative future/promise class.
    
    Two scenarios are supported:
    1. Do something when all async actions in loop are complete.
    2. Aggregate several typical async-callback functions result into one callback call.
    
    Example of 1:
      promise = new Future
      result = []
      for i in [1..10]
        promise.fork()
        setTimeout ->
          result.push(i)
          promise.resolve()
        , 1000
      promise.done ->
        _console.log result.join(', ')
    
    Example of 2:
      asyncGetter = (key, callback) ->
        obj =
          test: [1, 2, 3, 4, 5]
        setTimeout ->
          callback(obj[key])
        , 500
    
      promise = new Future
      require ['jquery', 'underscore'], promise.callback()
      asyncGetter 'test', promise.callback()
      promise.done ($, _, testVal) ->
        $('body').html("Even vals of 'test' = #{ _.filter(testVal, (num) -> num % 2 == 0) }")
    */

    Future.prototype._counter = 0;

    Future.prototype._doneCallbacks = null;

    Future.prototype._failCallbacks = null;

    Future.prototype._alwaysCallbacks = null;

    Future.prototype._order = 0;

    Future.prototype._callbackArgs = null;

    Future.prototype._locked = false;

    Future.prototype._completed = false;

    Future.prototype._state = 'pending';

    Future.prototype._name = '';

    function Future(initialCounter, name) {
      if (initialCounter == null) {
        initialCounter = 0;
      }
      if (name == null) {
        name = '';
      }
      /*
      @param (optional)Int initialCounter initial state of counter, syntax sugar to avoid (new Future).fork().fork()
      @param (optional)String name individual name of the future to separate it from others during debugging
      */

      if ((initialCounter != null) && _.isString(initialCounter)) {
        name = initialCounter;
        initialCounter = 0;
      }
      this._counter = initialCounter;
      this._doneCallbacks = [];
      this._failCallbacks = [];
      this._alwaysCallbacks = [];
      this._name = name;
    }

    Future.prototype.fork = function() {
      /*
      Adds one more value to wait.
      Should be paired with following resolve() call.
      @return Future(self)
      */

      if (this._completed && !(this._state === 'rejected' && this._counter > 0)) {
        throw Error("Trying to use the completed promise!");
      }
      if (this._locked) {
        throw Error("Trying to fork locked promise!");
      }
      this._counter++;
      return this;
    };

    Future.prototype.resolve = function() {
      var args, nameStr;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      /*
      Indicates that one of the waiting values is ready.
      If there are some arguments passed then they are passed unchanged to the done-callbacks.
      If there is no value remaining in the aggregate and done method is already called
       than callback is fired immedialtely.
      Should have according fork() call before.
      */

      if (this._counter > 0) {
        this._counter--;
        if (this._state !== 'rejected') {
          if (args.length > 0) {
            this._callbackArgs = [args];
          }
          if (this._counter === 0) {
            if (this._doneCallbacks.length > 0) {
              this._runDoneCallbacks();
            }
            if (this._alwaysCallbacks.length > 0) {
              this._runAlwaysCallbacks();
            }
          }
        }
      } else {
        nameStr = this._name ? " (name = " + this._name + ")" : '';
        throw new Error("Future::resolve() is called more times than Future::fork!" + nameStr);
      }
      return this;
    };

    Future.prototype.reject = function(err) {
      /*
      Indicates that the promise is rejected (failed) and fail-callbacks should be called.
      If there are some arguments passed then they are passed unchanged to the fail-callbacks.
      If fail-method is already called than callbacks are fired immediately, otherwise they'll be fired
       when fail-method is called.
      Only first call of this method is important. Any subsequent calls does nothing but decrementing the counter.
      */

      if (this._counter > 0) {
        this._counter--;
        if (this._state !== 'rejected') {
          this._state = 'rejected';
          this._callbackArgs = [err != null ? err : 'Future rejected without error message!'];
          if (this._failCallbacks.length > 0) {
            this._runFailCallbacks();
          }
          if (this._alwaysCallbacks.length > 0) {
            this._runAlwaysCallbacks();
          }
        }
      } else {
        throw new Error("Future::reject is called more times than Future::fork!");
      }
      return this;
    };

    Future.prototype.complete = function() {
      var args, err;
      err = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      /*
      Completes this promise either with successful of failure result depending on the arguments.
      If first argument is not null than the promise is completed with reject using first argument as an error.
      Otherwise remainin arguments are used for promise.resolve() call.
      This method is useful to work with lots of APIs using such semantics of the callback agruments.
      */

      if (err != null) {
        return this.reject(err);
      } else {
        return this.resolve.apply(this, args);
      }
    };

    Future.prototype.when = function() {
      var args, promise, _i, _len,
        _this = this;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      /*
      Adds another future(promise)(s) as a condition of completion of this future
      Can be called multiple times.
      @param (variable)Future args another future which'll be waited
      @return Future self
      */

      for (_i = 0, _len = args.length; _i < _len; _i++) {
        promise = args[_i];
        if (!this._locked) {
          this.fork();
        }
        promise.done(function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return _this.resolve.apply(_this, args);
        }).fail(function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return _this.reject.apply(_this, args);
        });
      }
      return this;
    };

    Future.prototype.link = function(anotherPromise) {
      /*
      Inversion of `when` method. Tells that the given future will complete when this future will complete.
      Just syntax sugar to convert anotherFuture.when(future) to future.link(anotherFuture).
      In some cases using link instead of when leads to more elegant code.
      @param Future anotherFuture
      @return Future self
      */

      anotherPromise.when(this);
      return this;
    };

    Future.prototype.done = function(callback) {
      /*
      Defines callback function to be called when future is resolved.
      If all waiting values are already resolved then callback is fired immedialtely.
      If done method is called several times than all passed functions will be called.
      */

      this._doneCallbacks.push(callback);
      if (this._counter === 0 && this._state !== 'rejected') {
        this._runDoneCallbacks();
      }
      return this;
    };

    Future.prototype.fail = function(callback) {
      /*
      Defines callback function to be called when future is rejected.
      If all waiting values are already resolved then callback is fired immedialtely.
      If done method is called several times than all passed functions will be called.
      */

      if (!_.isFunction(callback)) {
        throw new Error("Invalid argument for Future.fail(): " + callback);
      }
      this._failCallbacks.push(callback);
      if (this._state === 'rejected') {
        this._runFailCallbacks();
      }
      return this;
    };

    Future.prototype.always = function(callback) {
      /*
      Defines callback funtion to be called when future is completed by any mean.
      Callback arguments are using popular semantics with first-argument-as-an-error (Left) and other arguments
       are successful results of the future.
      */

      this._alwaysCallbacks.push(callback);
      if (this._counter === 0) {
        this._runAlwaysCallbacks();
      }
      return this;
    };

    Future.prototype.failAloud = function() {
      /*
      Adds often-used scenario of fail that just throws exception with the error
      */

      return this.fail(throwExceptionCallback);
    };

    Future.prototype.callback = function() {
      var neededArgs, order,
        _this = this;
      neededArgs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      /*
      Generates callback proxy function to be used in return-in-async-callback functions
       which allows to avoid callback-indentation hell by merging callback callback calls
       of severar such functions into one callback which is called when all async functions
       are complete.
      
      All arguments of aggregated callbacks are passed to 'done'-defined callback in order of calling
       'callback' method.
      
      @see example 2 in class documentation block
      */

      this.fork();
      order = this._order++;
      if (this._callbackArgs == null) {
        this._callbackArgs = {};
      }
      return function() {
        var args, i, result, _i, _len;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (_this._state !== 'rejected') {
          if (neededArgs.length) {
            result = [];
            for (_i = 0, _len = neededArgs.length; _i < _len; _i++) {
              i = neededArgs[_i];
              result.push(args[i]);
            }
          } else {
            result = args;
          }
          _this._callbackArgs[order] = result;
        }
        return _this.resolve();
      };
    };

    Future.prototype.completed = function() {
      /*
      Indicates that callbacks() are already called at least once and fork() cannot be called anymore
      @return Boolean
      */

      if (!this._completed && this._counter === 0) {
        this._completed = true;
      }
      return this._completed;
    };

    Future.prototype.state = function() {
      /*
      Returns state of the promise - 'pending', 'resolved' or 'rejected'
      @return String
      */

      return this._state;
    };

    Future.prototype.lock = function() {
      this._locked = true;
      return this;
    };

    Future.prototype.map = function(callback) {
      /*
      Creates new Future by applying the given callback to the successful result of this Future.
      Resolves resulting future with the result of the callback.
      If callback returns an Array than it's considered as a list of results. If it is necessary to return a single
       array than callback must return an Array with single item containing the resulting Array (Array in Array).
      If this Future is rejected than the resulting Future will contain the same error.
      */

      var result;
      result = Future.single();
      this.done(function() {
        var args, mapRes;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        mapRes = callback.apply(null, args);
        if (_.isArray(mapRes)) {
          return result.resolve.apply(result, mapRes);
        } else {
          return result.resolve(mapRes);
        }
      });
      this.fail(function(err) {
        return result.reject(err);
      });
      return result;
    };

    Future.prototype.flatMap = function(callback) {
      /*
      Creates new Future by applying the given callback to the successful result of this Future.
      Returns result of the callback as a new Future.
      Callback must return a Future, and resulting Future is completed when the callback-returned future is completed.
      If this Future is rejected than the resulting Future will contain the same error.
      @param Function(this.result -> Future(A)) callback
      @return Future(A)
      */

      var result;
      result = Future.single();
      this.done(function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return result.when(callback.apply(null, args));
      });
      this.fail(function(err) {
        return result.reject(err);
      });
      return result;
    };

    Future.prototype.andThen = function(callback) {
      /*
      Creates and returns a new future with the same result as this future but completed only after invoking
       of the given callback-function. Callback is called on any result of the future.
      Arguments of the callback has the same meaning as always()-callbacks.
      This method allows for establishing order of callbacks.
      @param Function(err, results...) callback
      @return Future(this.result)
      */

      var result;
      result = Future.single();
      this.always(function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        callback.apply(null, args);
        return result.complete.apply(result, args);
      });
      return result;
    };

    Future.prototype.zip = function() {
      var those;
      those = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      /*
      Zips the values of this and that future, and creates a new future holding the tuple of their results.
      @param Future those another futures
      @return Future
      */

      those.unshift(this);
      return Future.sequence(those).map(function(result) {
        return result;
      });
    };

    Future.sequence = function(futureList) {
      /*
      Converts Array[Future[X]] to Future[Array[X]]
      */

      var f, i, promise, result, _fn, _i, _len;
      promise = new Future;
      result = [];
      _fn = function(i) {
        promise.fork();
        return f.done(function(res) {
          result[i] = res;
          return promise.resolve();
        });
      };
      for (i = _i = 0, _len = futureList.length; _i < _len; i = ++_i) {
        f = futureList[i];
        _fn(i);
      }
      return promise.map(function() {
        return [result];
      });
    };

    Future.select = function(futureList) {
      /*
      Returns new future which completes successfully when one of the given futures completes successfully (which comes
       first). Resulting future resolves with that first-completed future's result. All subsequent completing
       futures are ignored.
      Result completes with failure if all of the given futures fails.
      @param Array[Future[X]] futureList
      @return Future[X]
      */

      var f, failCounter, ready, result, _fn, _i, _len;
      result = this.single();
      ready = false;
      failCounter = futureList.length;
      _fn = function(f) {
        return f.done(function() {
          if (!ready) {
            result.when(f);
            return ready = true;
          }
        }).fail(function() {
          failCounter--;
          if (failCounter === 0) {
            return result.reject("All selecting futures have failed!");
          }
        });
      };
      for (_i = 0, _len = futureList.length; _i < _len; _i++) {
        f = futureList[_i];
        _fn(f);
      }
      return result;
    };

    Future.prototype._runDoneCallbacks = function() {
      /*
      Fires resulting callback functions defined by done with right list of arguments.
      */

      var callbacksCopy;
      this._state = 'resolved';
      callbacksCopy = this._doneCallbacks;
      this._doneCallbacks = [];
      return this._runCallbacks(callbacksCopy, true);
    };

    Future.prototype._runFailCallbacks = function() {
      /*
      Fires resulting callback functions defined by fail with right list of arguments.
      */

      var callbacksCopy;
      callbacksCopy = this._failCallbacks;
      this._failCallbacks = [];
      return this._runCallbacks(callbacksCopy);
    };

    Future.prototype._runAlwaysCallbacks = function() {
      /*
      Fires resulting callback functions defined by always with right list of arguments.
      */

      var args, callback, callbacksCopy, i, _i, _j, _len, _ref, _results;
      if (this._state === 'pending') {
        this._state = 'resolved';
      }
      callbacksCopy = this._alwaysCallbacks;
      this._alwaysCallbacks = [];
      this._completed = true;
      args = [];
      if (this._state === 'resolved') {
        args.push(null);
        if (this._callbackArgs != null) {
          for (i = _i = 0, _ref = this._order - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
            args = args.concat(this._callbackArgs[i]);
          }
        }
      } else {
        args = this._callbackArgs;
      }
      _results = [];
      for (_j = 0, _len = callbacksCopy.length; _j < _len; _j++) {
        callback = callbacksCopy[_j];
        _results.push(callback.apply(null, args));
      }
      return _results;
    };

    Future.prototype._runCallbacks = function(callbacks, flattenArgs) {
      var args, callback, i, _i, _j, _k, _len, _len1, _ref, _results, _results1;
      if (flattenArgs == null) {
        flattenArgs = false;
      }
      /*
      Helper-method to run list of callbacks.
      @param Array(Function) callbacks
      */

      this._completed = true;
      if (this._callbackArgs != null) {
        args = [];
        if (flattenArgs) {
          for (i = _i = 0, _ref = this._order - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
            args = args.concat(this._callbackArgs[i]);
          }
        } else {
          args = this._callbackArgs;
        }
        _results = [];
        for (_j = 0, _len = callbacks.length; _j < _len; _j++) {
          callback = callbacks[_j];
          _results.push(callback.apply(null, args));
        }
        return _results;
      } else {
        _results1 = [];
        for (_k = 0, _len1 = callbacks.length; _k < _len1; _k++) {
          callback = callbacks[_k];
          _results1.push(callback());
        }
        return _results1;
      }
    };

    Future.single = function(name) {
      if (name == null) {
        name = '';
      }
      /*
      Returns the future, which can not be forked and must be resolved by only single call of resolve().
      @return Future
      */

      return (new Future(1, name)).lock();
    };

    Future.resolved = function() {
      var args, result;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      /*
      Returns the future already resolved with the given arguments.
      @return Future
      */

      result = this.single();
      result.resolve.apply(result, args);
      return result;
    };

    Future.rejected = function(error) {
      /*
      Returns the future already rejected with the given error
      @param Any error
      @return Future
      */

      var result;
      result = this.single();
      result.reject(error);
      return result;
    };

    Future.call = function() {
      var args, fn, result;
      fn = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      /*
      Converts node-style function call with last-agrument-callback result to pretty composable future-result call.
      Node-style callback mean Function[err, A] - first argument if not-null means error and converts to
       Future.reject(), all subsequent arguments are treated as a successful result and passed to Future.resolve().
      Example:
        Traditional style:
          fs.readFile '/tmp/file', (err, data) ->
            throw err if err
            // do something with data
        Future-style:
          Future.call(fs.readFile, '/tmp/file').failAloud().done (data) ->
            // do something with data
      @param Function|Tuple[Object, String] fn callback-style function to be called (e.g. fs.readFile)
      @param Any args* arguments of that function without last callback-result argument.
      @return Future[A]
      */

      result = this.single();
      args.push(function() {
        var callbackArgs;
        callbackArgs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return result.complete.apply(result, callbackArgs);
      });
      if (_.isArray(fn)) {
        fn[0][fn[1]].apply(fn[0], args);
      } else {
        fn.apply(null, args);
      }
      return result;
    };

    Future.timeout = function(millisec) {
      /*
      Returns the future wich will complete after the given number of milliseconds
      @param Int millisec number of millis before resolving the future
      @return Future
      */

      var result;
      result = this.single();
      setTimeout(function() {
        return result.resolve();
      }, millisec);
      return result;
    };

    Future.require = function() {
      var paths, result;
      paths = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      /*
      Convenient Future-wrapper for requirejs's require call.
      @param String* paths list of modules requirejs-format paths
      @return Future(modules...)
      */

      result = this.single();
      require(paths, function() {
        var modules;
        modules = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return result.resolve.apply(result, modules);
      }, function(err) {
        return result.reject(err);
      });
      return result;
    };

    Future.prototype._debug = function() {
      var args, fn;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      /*
      Debug logging method, which logs future's name, counter, callback lenght, and given arguments.
      Can emphasise futures with desired names by using console.warn.
      */

      if (this._name.indexOf('desired search in name') !== -1) {
        fn = _console.warn;
      } else {
        fn = _console.log;
      }
      args.unshift(this._name);
      args.unshift(this._doneCallbacks.length);
      args.unshift(this._counter);
      return fn.apply(_console, args);
    };

    return Future;

  })();
};

module.exports = defineFuture(require('underscore'));
