// Generated by CoffeeScript 1.9.1
var Future, fs, path, rmrf;

fs = require('fs');

path = require('path');

Future = require('./Future');

rmrf = function(target) {

  /*
  Recursively removes the given directory or file.
  Doesn't remove short top-level names (e.g. /usr/ or /etc/) to avoid fatal mistakes, name length must be greater than 5
  @param String target absolute path to the file/directory to be removed
  @return Future
   */
  if (path.resolve(target) === path.normalize(target) && target.trim().length > 5) {
    return Future.call(fs.lstat, target).flatMap(function(stat) {
      if (stat.isDirectory()) {
        return Future.call(fs.readdir, target).flatMap(function(items) {
          var futures, item;
          futures = (function() {
            var i, len, results;
            results = [];
            for (i = 0, len = items.length; i < len; i++) {
              item = items[i];
              results.push(rmrf(path.join(target, item)));
            }
            return results;
          })();
          return Future.sequence(futures);
        }).flatMap(function() {
          return Future.call(fs.rmdir, target);
        });
      } else {
        return Future.call(fs.unlink, target);
      }
    }).flatMapFail(function(err) {
      if (err.code === 'ENOENT') {
        return Future.resolved();
      } else {
        return Future.rejected(err);
      }
    });
  } else {
    return Future.rejected(new Error("Only absolute and not short top-level paths are supported, '" + target + "' given!"));
  }
};

module.exports = rmrf;
